const DEFAULT_HTTP_PORT = 80;
const DEFAULT_HTTPS_PORT = 443;
const DEFAULT_HOSTNAME = "localhost";
const DEFAULT_TIMEOUT = 30000;

export {
	DEFAULT_HTTP_PORT,
	DEFAULT_HOSTNAME,
	DEFAULT_HTTPS_PORT,
	DEFAULT_TIMEOUT,
}
